// STEP-2 - DESIGN THE TYPES OF ACTIONS THAT MIGHT SUFFER
export const INPUT_CHANGE = 'INPUT_CHANGE'
export const ADD_TODO = 'ADD_TODO'
export const COMPLETED = 'COMPLETED'
export const REMOVE = 'REMOVE'
